'use client';

/**
 * Documents — SRS §20.5, §33's "Documents", checklist row 4.4.
 *
 * ## The one screen with no module gate, and the reason is worth knowing
 *
 * Every other module router mounts `requireModule(...)`. This one mounts
 * `requireActiveSubscription()` instead, because §20.5's seven document types span **four**
 * subscribable modules — `DOCUMENT_TYPE_MODULE` maps them onto `id_cards`, `certificates`, `fees`
 * and `exams`. There is no single key to gate on, so the module check happens per document type
 * inside the service.
 *
 * That has a visible consequence: this screen can load and list documents while a *particular* type
 * is still unavailable. A refusal on generating one is not a refusal of the screen.
 *
 * ## `file_path` never arrives, and that is the design
 *
 * `documents.service.js:128-132` deletes it and returns `has_file` instead. The bytes come from
 * `GET /documents/{id}?format=pdf`, which re-checks the tenant on the way out. A column showing the
 * path would be showing a value the API deliberately withholds — and one that was null anyway.
 *
 * ## The teacher and the exam come from the documents pick-lists — owner decision D34
 *
 * FR-DOC-001 names the Accountant and the Receptionist as actors, and neither holds `teachers.view`
 * or `exams.view` — so a Teacher ID Card and a Result Card, the two documents that name a teacher and
 * an exam, could not be generated by exactly the people the requirement names: the dialog read
 * `GET /teachers` and `GET /exams` and got nothing. D34 answered with two small lists under the key
 * that opens this dialog, `documents.generate`: `GET /documents/pickers/teachers` and
 * `/documents/pickers/exams`. The dialog reads them for **every** caller rather than only for one
 * without the view keys: they answer the same question on the key the dialog already requires, and
 * they sit on this router, which checks the subscription's state and not the Teachers or Exams module
 * — so one code path serves every actor, and a grant edited later cannot empty the list. Both take
 * `q` and return at most fifty, with no total; the hints say when a list may have been cut there.
 */

import { useCallback, useEffect, useMemo, useState } from 'react';
import type { FormEvent } from 'react';

import { ApiError, api, saveFile } from '@/lib/apiClient';
import { useAuth } from '@/lib/auth';
import { useCollection } from '@/lib/useCollection';
import { splitApiErrors } from '@/lib/formErrors';
import { formatAmountWithCode } from '@/lib/money';
import { localDay } from '@/lib/instants';
import { OPTION_LIMIT } from '@/lib/useTimetablePickers';
import {
  Field,
  Notice,
  SearchField,
  SelectField,
  SubmitButton,
  TextAreaField,
  FilterBar,
  FilterSelect,
  focusFirstInvalidField,
} from '@/components/form';
import { Icon, Spinner } from '@/components/icon';
import { Modal } from '@/components/overlay';
import { useToast } from '@/components/toast';
import {
  Column,
  DataTable,
  EmptyNotice,
  ErrorNotice,
  LoadingBlock,
  PageHeader,
  Pagination,
  RefusalNotice,
} from '@/components/table';

interface DocumentRow {
  id: number;
  document_type: string;
  owner_type: string;
  owner_id: number;
  title: string;
  file_name: string | null;
  mime_type: string | null;
  file_size_bytes: number | null;
  is_generated: boolean;
  generated_at: string | null;
  description: string | null;
  created_at: string;
  /* `present()` adds this in place of the path it removes. */
  has_file: boolean;
}

/** §20.5's seven types, for the filter. There is no endpoint that lists them. */
const TYPES = [
  'student_id_card',
  'teacher_id_card',
  'admission_form',
  'fee_receipt',
  'result_card',
  'character_certificate',
  'leaving_certificate',
];

/**
 * `leaving_certificate` -> `Leaving certificate`.
 *
 * One helper rather than the four inline `.replace(/_/g, ' ')` calls this file had, which
 * differed in whether they capitalised. Sentence case, because these are labels.
 */
function humanise(value: string): string {
  return value.replace(/_/g, ' ').replace(/^./, (first) => first.toUpperCase());
}

function fileSize(bytes: number | null) {
  if (bytes === null) return <span className="text-muted-soft">—</span>;
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export default function DocumentsPage() {
  const { can } = useAuth();
  const { success, error: errorToast } = useToast();

  const [page, setPage] = useState(1);
  const [search, setSearch] = useState('');
  const [debounced, setDebounced] = useState('');
  const [documentType, setDocumentType] = useState('');

  /*
   * 300 ms, as every other search screen does. `useCollection` refetches on every change to the
   * query and holds no timer of its own, so feeding `search` straight in sent one request per
   * keystroke — ten for a ten-character title.
   */
  useEffect(() => {
    const timer = setTimeout(() => {
      setDebounced(search);
      /*
       * Resetting to page one is part of the search, not a separate concern — searching from page
       * three and staying there shows an empty table for a query that has two pages of results.
       */
      setPage(1);
    }, 300);
    return () => clearTimeout(timer);
  }, [search]);

  const query = useMemo(
    () => ({ page, limit: 20, q: debounced || undefined, document_type: documentType || undefined }),
    [page, debounced, documentType]
  );
  const { rows, meta, loading, error, refusal, reload } = useCollection<DocumentRow>('/documents', query);

  const canGenerate = can('documents.generate');

  const [generating, setGenerating] = useState(false);
  /** The row whose PDF is being fetched, so only that button spins. */
  const [downloading, setDownloading] = useState<number | null>(null);

  /*
   * `useCallback`, because the columns memo captures it. See the note on the taxes screen:
   * without it the memo holds whichever copy existed when its own dependencies last changed,
   * and is correct only by accident of what the handler happens to read.
   */
  const downloadPdf = useCallback(async (row: DocumentRow) => {
    setDownloading(row.id);
    try {
      const file = await api.download(
        `/documents/${row.id}`,
        { query: { format: 'pdf' } },
        `${row.document_type}-${row.id}.pdf`
      );
      saveFile(file);
    } catch (caught) {
      errorToast(
        'Could not produce that PDF',
        caught instanceof ApiError ? caught.message : undefined
      );
    } finally {
      setDownloading(null);
    }

  }, [errorToast]);

  const columns = useMemo<Column<DocumentRow>[]>(
    () => [
      { key: 'title', header: 'Title', cell: (row) => <span className="font-medium">{row.title}</span> },
      { key: 'type', header: 'Type', cell: (row) => humanise(row.document_type) },
      {
        key: 'owner',
        header: 'Belongs to',
        /*
         * A polymorphic owner: `owner_type` plus `owner_id`, with no association to include because
         * the target table varies by row. The id is shown because it is all there is — and unlike a
         * plain foreign key, the type beside it makes the pair meaningful.
         */
        cell: (row) => (
          <>
            {humanise(row.owner_type)}
            <span className="ml-1 text-muted-soft">#{row.owner_id}</span>
          </>
        ),
      },
      {
        key: 'origin',
        header: 'Origin',
        /*
         * Generated and uploaded documents behave differently — a generated one can be regenerated
         * from `generation_payload`, an uploaded one cannot — so the distinction earns a column.
         */
        cell: (row) =>
          row.is_generated ? (
            <>
              generated
              {row.generated_at ? (
                <span className="block text-xs text-muted-soft">{row.generated_at.slice(0, 10)}</span>
              ) : null}
            </>
          ) : (
            'uploaded'
          ),
      },
      {
        key: 'file',
        header: 'File',
        cell: (row) =>
          row.has_file ? (
            <>
              {row.file_name ?? 'file'}
              <span className="block text-xs text-muted-soft">{fileSize(row.file_size_bytes)}</span>
            </>
          ) : (
            /*
             * A row with no file is normal rather than broken: §22 established that generated
             * artefacts are streamed on request instead of being written to disk, so a generated
             * document usually has a payload and no stored file.
             */
            <span className="text-muted-soft">streamed on request</span>
          ),
      },
      {
        /*
         * The control this cell used to promise and not offer.
         *
         * "streamed on request" was true and there was **no way to make the request**: nothing in
         * the frontend fetched `GET /documents/:id?format=pdf`, which `documents.controller.js`
         * has answered with a PDF Buffer and an attachment header since Phase 5.4. So an accountant
         * who needed a fee receipt could see that one had been generated and could not obtain it.
         *
         * A plain `<a href>` will not do: `readBearerToken` reads the `Authorization` header only,
         * so an unadorned navigation is a 401. The bytes come through `api.download` and go to the
         * browser's save flow via `saveFile`.
         */
        key: 'download',
        header: 'PDF',
        cell: (row) => (
          <button
            type="button"
            onClick={() => void downloadPdf(row)}
            disabled={downloading === row.id}
            aria-busy={downloading === row.id}
            className="btn btn-ghost btn-sm"
          >
            {downloading === row.id ? <Spinner size={13} /> : <Icon name="download" size={14} />}
            {downloading === row.id ? 'Preparing…' : 'PDF'}
          </button>
        ),
      },
    ],
    [downloading, downloadPdf]
  );

  return (
    <div>
      <PageHeader
        title="Documents"
        description="Generated and uploaded records — §20.5's seven types."
        action={
          /* `documents.generate` is the key `POST /documents` is mounted behind. */
          canGenerate ? (
            <button type="button" onClick={() => setGenerating(true)} className="btn btn-primary">
              <Icon name="plus" size={15} />
              Generate a document
            </button>
          ) : undefined
        }
      />

      <FilterBar
        activeCount={[documentType, search].filter(Boolean).length}
        onClear={() => {
          setDocumentType('');
          setSearch('');
          setPage(1);
        }}
      >
        <div>
          {/*
            * "Title", not "Title or description". `documents.service.js` builds this filter as
            * `where.title = { [Op.like]: … }` and touches nothing else, so the old placeholder
            * promised a description search that never happened — a box that looks like it worked and
            * returns too few rows, which is the failure mode this codebase keeps naming and keeps
            * re-introducing in the label rather than the query.
            */}
          <SearchField
            id="document-search"
            label="Search documents by title"
            placeholder="Search by title…"
            value={search}
            onChange={setSearch}
          />
        </div>
        <div>
          <FilterSelect
            id="document-type"
            label="Document type"
            value={documentType}
            onChange={(value) => { setDocumentType(value); setPage(1); }}
          >
            <option value="">Any type</option>
            {TYPES.map((type) => (
              <option key={type} value={type}>
                {humanise(type)}
              </option>
            ))}
          </FilterSelect>
        </div>
      </FilterBar>

      {refusal ? (
        <RefusalNotice refusal={refusal} />
      ) : error ? (
        <ErrorNotice message={error} onRetry={reload} />
      ) : loading && rows.length === 0 ? (
        <LoadingBlock />
      ) : rows.length === 0 ? (
        <EmptyNotice>
          {debounced || documentType ? 'No document matches these filters.' : 'No documents yet.'}
        </EmptyNotice>
      ) : (
        <>
          <DataTable columns={columns} rows={rows} rowKey={(row) => row.id} caption="Documents"
            busy={loading}
          />
          {meta ? <Pagination meta={meta} onPage={setPage} /> : null}
        </>
      )}

      <GenerateDialog
        open={generating}
        onClose={() => setGenerating(false)}
        onDone={(name) => {
          setGenerating(false);
          success(`${name} generated`, 'Download it as a PDF from the list.');
          reload();
        }}
      />
    </div>
  );
}

/* ─────────────── generating one ─────────────── */

/**
 * Which record each document type is *about*.
 *
 * `documents.service.js` `OWNER_OF` is the authority and this mirrors it: `owner_type` is **derived
 * from the type, never supplied**, so the caller sends only an id — and which list that id has to
 * come from is exactly what this table decides. Five of the seven are about a student, one about a
 * teacher, and the fee receipt about a **`fee_payments` row** (§17's school-side receipt, not
 * §13's subscription payment, which is the platform billing the school).
 *
 * Getting this wrong is not an error a user could diagnose: the service loads the record in the
 * caller's school and refuses when it is absent, so a teacher id sent for a student document reads
 * as "that student does not exist".
 */
const OWNER_OF: Record<string, 'student' | 'teacher' | 'payment'> = {
  student_id_card: 'student',
  teacher_id_card: 'teacher',
  admission_form: 'student',
  fee_receipt: 'payment',
  result_card: 'student',
  character_certificate: 'student',
  leaving_certificate: 'student',
};

/** What the owner picker is called, per owner kind. */
const OWNER_LABEL: Record<string, string> = {
  student: 'Student',
  teacher: 'Teacher',
  payment: 'Fee payment',
};

/**
 * Where each owner list is read from, and what its `q` scans — the placeholder names exactly those
 * columns, because a search box that silently ignores the field a person typed is a box that looks
 * broken. `students.service.js` LIKEs name, student ID and roll number; `documents.service.js
 * pickTeachers()` the first name, the last name and the employee ID, each on its own — so a full
 * name typed with a space matches nothing, which is why the placeholder names the three separately;
 * `fees.service.js listPayments()` receipt number and reference, and not the student, which is why
 * the placeholder for receipts does not offer a name.
 */
const OWNER_SEARCH: Record<'student' | 'teacher' | 'payment', { noun: string; placeholder: string }> = {
  student: { noun: 'students', placeholder: 'Search by name, student ID or roll number…' },
  teacher: { noun: 'teachers', placeholder: 'Search by first name, last name or employee ID…' },
  payment: { noun: 'fee payments', placeholder: 'Search by receipt number or reference…' },
};

/** `documents.validation.js pickerQuery` caps `limit` at fifty, and the pick-lists send no total. */
const PICKER_LIMIT = 50;

/** One choosable owner, already worded — the three lists have three shapes and one picker. */
interface OwnerOption {
  id: number;
  label: string;
}

/** The fields this dialog renders. Anything else a 422 names goes to the banner. */
const FORM_FIELDS = new Set([
  'document_type',
  'owner_id',
  'exam_id',
  'title',
  'description',
  'reason',
]);

interface StudentOwner {
  id: number;
  student_id: string;
  first_name: string;
  last_name: string | null;
}

/** One row of `GET /documents/pickers/teachers` — the six attributes `pickTeachers()` selects. */
interface TeacherPick {
  id: number;
  employee_id: string;
  first_name: string;
  last_name: string | null;
  designation: string | null;
  is_active: boolean;
}

interface PaymentOwner {
  id: number;
  receipt_number: string | null;
  amount: number | string;
  currency: string | null;
  paid_at: string | null;
  /* `listPayments()` includes the student, so a receipt can say whose it is. A LEFT JOIN. */
  student?: { first_name: string; last_name: string | null } | null;
}

function personName(row: { first_name: string; last_name: string | null }): string {
  return [row.first_name, row.last_name].filter(Boolean).join(' ');
}

/**
 * One row of `GET /documents/pickers/exams`. `pickExams()` joins the class and the section with
 * their names — a LEFT JOIN each, and the section is NULL for an exam every section sits.
 */
interface ExamPick {
  id: number;
  name: string;
  exam_type: string | null;
  status: string;
  start_date: string | null;
  class: { id: number; name: string } | null;
  section: { id: number; name: string } | null;
}

/** `Mid-term — Grade 7, section B (published)`: which exam, who sat it, and how far it has got. */
function examLabel(exam: ExamPick): string {
  const who = exam.class
    ? `${exam.class.name}${exam.section ? `, section ${exam.section.name}` : ''}`
    : null;
  return `${who ? `${exam.name} — ${who}` : exam.name} (${exam.status.replace(/_/g, ' ')})`;
}

function GenerateDialog({
  open,
  onClose,
  onDone,
}: {
  open: boolean;
  onClose: () => void;
  onDone: (name: string) => void;
}) {
  const [documentType, setDocumentType] = useState('');
  const [ownerId, setOwnerId] = useState('');
  const [examId, setExamId] = useState('');
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [busy, setBusy] = useState(false);
  const [failure, setFailure] = useState<string | null>(null);
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});

  /*
   * The owner picker's state. Rows are held already worded as `OwnerOption`s — the three lists have
   * three shapes, and wording each row once, as it arrives, keeps one picker below instead of three.
   */
  const [owners, setOwners] = useState<OwnerOption[]>([]);
  /* `null` for the teacher pick-list, which sends no total — see `PICKER_LIMIT`. */
  const [ownerTotal, setOwnerTotal] = useState<number | null>(0);
  const [ownersFailed, setOwnersFailed] = useState(false);
  const [ownerSearch, setOwnerSearch] = useState('');
  const [ownerQuery, setOwnerQuery] = useState('');
  /*
   * The chosen owner, remembered as an option and not only as an id. Searching again replaces the
   * list, and a choice outside the new page would otherwise leave the select blank while `ownerId`
   * still held it — the form would generate a document about someone it no longer shows.
   */
  const [pinnedOwner, setPinnedOwner] = useState<OwnerOption | null>(null);

  /* The exam picker, searched the same way and for the same reason — see D34 in the header. */
  const [exams, setExams] = useState<ExamPick[]>([]);
  const [examsFailed, setExamsFailed] = useState(false);
  const [examSearch, setExamSearch] = useState('');
  const [examQuery, setExamQuery] = useState('');
  const [pinnedExam, setPinnedExam] = useState<ExamPick | null>(null);

  const ownerKind = documentType ? OWNER_OF[documentType] : null;
  const needsExam = documentType === 'result_card';

  useEffect(() => {
    if (!open) return;
    setDocumentType('');
    setOwnerId('');
    setExamId('');
    setTitle('');
    setDescription('');
    setOwnerSearch('');
    setOwnerQuery('');
    setPinnedOwner(null);
    setExamSearch('');
    setExamQuery('');
    setPinnedExam(null);
    setBusy(false);
    setFailure(null);
    setFieldErrors({});
  }, [open]);

  /* 300 ms, as every search box here waits: `apiLimiter` sits in front of each keystroke. */
  useEffect(() => {
    const timer = setTimeout(() => setOwnerQuery(ownerSearch.trim()), 300);
    return () => clearTimeout(timer);
  }, [ownerSearch]);

  useEffect(() => {
    const timer = setTimeout(() => setExamQuery(examSearch.trim()), 300);
    return () => clearTimeout(timer);
  }, [examSearch]);

  /*
   * The owner list is fetched **once a type is chosen**, not up front: three of the four would be
   * wasted on any given document, and the payments list in particular is the school's whole receipt
   * history. A failure says so rather than leaving an empty dropdown that reads as "none exist".
   *
   * ## A search, because one page of a hundred was not the school
   *
   * This loaded the first hundred rows of the list and said "Anything beyond that cannot be picked
   * here" — so a leaving certificate for the 101st student alphabetically, or a receipt from last
   * term, could not be generated from the one screen that generates them, although FR-DOC-001's
   * outcome is a document "for the relevant student/teacher/record" (SRS:1136). All three lists accept
   * `q`, so the list is searched rather than truncated: the first page still arrives unasked, and
   * typing narrows it on the server — the shape the account pickers on the create screens already use.
   */
  useEffect(() => {
    if (!open || !ownerKind) return;
    const controller = new AbortController();
    const query = { limit: OPTION_LIMIT, q: ownerQuery || undefined };

    (async () => {
      try {
        let rows: OwnerOption[];
        let total: number | null;
        if (ownerKind === 'student') {
          const page = await api.page<StudentOwner[]>('/students', { query, signal: controller.signal });
          rows = (page.data ?? []).map((row) => ({
            id: row.id,
            label: `${personName(row)} (${row.student_id})`,
          }));
          total = page.meta?.total ?? rows.length;
        } else if (ownerKind === 'teacher') {
          /*
           * D34's pick-list, not `GET /teachers` — see the header. Not a page: `{ teachers }`, at most
           * `PICKER_LIMIT`, and no total, so `null` tells the hint it can only say "the first fifty".
           */
          const body = await api.get<{ teachers: TeacherPick[] }>('/documents/pickers/teachers', {
            query: { q: ownerQuery || undefined, limit: PICKER_LIMIT },
            signal: controller.signal,
          });
          rows = (body.teachers ?? []).map((row) => ({
            id: row.id,
            label: `${personName(row)} (${row.employee_id})${row.designation ? ` — ${row.designation}` : ''}${
              row.is_active ? '' : ' — inactive'
            }`,
          }));
          total = null;
        } else {
          const page = await api.page<PaymentOwner[]>('/fees/payments', { query, signal: controller.signal });
          /*
           * The receipt, the amount, whose it was and when — a receipt number alone is a string of
           * digits, and the student and the day are what someone asking for a copy actually knows.
           */
          rows = (page.data ?? []).map((row) => ({
            id: row.id,
            label: [
              row.receipt_number ?? `payment #${row.id}`,
              formatAmountWithCode(row.amount, row.currency),
              row.student ? personName(row.student) : null,
              localDay(row.paid_at),
            ]
              .filter(Boolean)
              .join(' — '),
          }));
          total = page.meta?.total ?? rows.length;
        }
        if (controller.signal.aborted) return;
        setOwners(rows);
        setOwnerTotal(total);
        setOwnersFailed(false);
      } catch {
        if (controller.signal.aborted) return;
        setOwners([]);
        setOwnerTotal(0);
        setOwnersFailed(true);
      }
    })();

    return () => controller.abort();
  }, [open, ownerKind, ownerQuery]);

  /*
   * Exams only for a result card — `exam_id` is `forbidden()` on every other type. D34's pick-list,
   * newest first (`pickExams()` orders by `start_date DESC`), searched by name. It used to read the
   * first hundred of `GET /exams` with no search at all, so an older exam could not be chosen; and it
   * swallowed a failure, leaving an empty select that read as "this school has no exams".
   */
  useEffect(() => {
    if (!open || !needsExam) return;
    const controller = new AbortController();

    (async () => {
      try {
        const body = await api.get<{ exams: ExamPick[] }>('/documents/pickers/exams', {
          query: { q: examQuery || undefined, limit: PICKER_LIMIT },
          signal: controller.signal,
        });
        if (controller.signal.aborted) return;
        setExams(body.exams ?? []);
        setExamsFailed(false);
      } catch {
        if (controller.signal.aborted) return;
        setExams([]);
        setExamsFailed(true);
      }
    })();

    return () => controller.abort();
  }, [open, needsExam, examQuery]);

  /* The pinned choice first when the current page does not hold it — see `pinnedOwner`. */
  const ownerOptions =
    pinnedOwner && !owners.some((row) => row.id === pinnedOwner.id) ? [pinnedOwner, ...owners] : owners;
  const examOptions =
    pinnedExam && !exams.some((row) => row.id === pinnedExam.id) ? [pinnedExam, ...exams] : exams;

  /*
   * Built here because `SelectField` takes its hint as a string, and each sentence is true only
   * sometimes. A list with a total says how many it holds; the teacher pick-list has none, so a full
   * one can only say it may have been cut.
   */
  const ownerCapped = ownerTotal === null ? owners.length >= PICKER_LIMIT : ownerTotal > owners.length;
  const ownerHint = !ownerKind
    ? undefined
    : ownerCapped
      ? ownerTotal === null
        ? `Showing the first ${owners.length} ${OWNER_SEARCH[ownerKind].noun} — search to narrow the list.`
        : `Showing ${owners.length} of ${ownerTotal} ${OWNER_SEARCH[ownerKind].noun} — search to narrow the list.`
      : ownerQuery && owners.length === 0
        ? `No ${OWNER_SEARCH[ownerKind].noun} match “${ownerQuery}”.`
        : undefined;

  const examHint =
    exams.length >= PICKER_LIMIT
      ? `The newest ${exams.length} exams${examQuery ? ` matching “${examQuery}”` : ''} — search by name for an older one.`
      : examQuery && exams.length === 0
        ? `No exams match “${examQuery}”.`
        : 'A result card is about one exam, and needs that student’s result in it to be published.';

  async function submit(event: FormEvent) {
    event.preventDefault();
    setBusy(true);
    setFailure(null);
    setFieldErrors({});

    try {
      /*
       * `exam_id` goes **only** with a result card. The schema does not merely ignore it elsewhere
       * — it is `Joi.forbidden()` with its own message — so a value left over from a type the
       * user changed away from would be a 422 naming a field no longer on screen.
       */
      const body: Record<string, unknown> = {
        document_type: documentType,
        owner_id: Number(ownerId),
        title: title.trim() || undefined,
        description: description.trim() || undefined,
      };
      if (needsExam) body.exam_id = Number(examId);

      const result = await api.post<{ document: { title: string } }>('/documents', body);
      onDone(result.document?.title ?? 'Document');
    } catch (caught) {
      if (!(caught instanceof ApiError)) throw caught;
      const { perField, banner } = splitApiErrors(caught, FORM_FIELDS);
      setFieldErrors(perField);
      setFailure(banner);
      if (Object.keys(perField).length) focusFirstInvalidField();
    } finally {
      setBusy(false);
    }
  }

  return (
    <Modal
      open={open}
      onClose={onClose}
      title="Generate a document"
      description="The record is built from what the underlying row holds right now and keeps that snapshot, so a certificate reissued later says what it said when it was issued."
      busy={busy}
      footer={
        <>
          <button type="button" onClick={onClose} disabled={busy} className="btn btn-secondary">
            Cancel
          </button>
          <SubmitButton form="generate-document" busy={busy} busyLabel="Generating…">
            Generate
          </SubmitButton>
        </>
      }
    >
      <form id="generate-document" onSubmit={submit} className="space-y-4" noValidate>
        {failure ? <Notice tone="error">{failure}</Notice> : null}

        <SelectField
          id="document_type"
          label="Document"
          required
          value={documentType}
          onChange={(event) => {
            const nextKind = event.target.value ? OWNER_OF[event.target.value] : null;
            setDocumentType(event.target.value);
            /* The owner list changes with the type, so a carried-over id would name the wrong row. */
            setOwnerId('');
            setExamId('');
            setPinnedOwner(null);
            setPinnedExam(null);
            /*
             * A different kind of owner is a different list: the old rows and the old search would
             * otherwise be offered for a moment as though they were the new kind's.
             */
            if (nextKind !== ownerKind) {
              setOwners([]);
              setOwnerTotal(0);
              setOwnerSearch('');
              setOwnerQuery('');
            }
          }}
          error={fieldErrors.document_type}
          hint="Each type is about one kind of record, which decides who you pick below."
        >
          <option value="">Choose a document</option>
          {TYPES.map((value) => (
            <option key={value} value={value}>
              {humanise(value)}
            </option>
          ))}
        </SelectField>

        {ownerKind ? (
          <>
            {ownersFailed ? (
              <Notice tone="warn">
                The {OWNER_LABEL[ownerKind].toLowerCase()} list could not be loaded, so there is
                nothing to choose from.{' '}
                {ownerKind === 'teacher'
                  ? 'It is the documents pick-list, read on the same permission as generating, so close this dialog and open it again to retry.'
                  : 'That list needs its own view permission, separate from generating documents.'}
              </Notice>
            ) : null}

            {/*
              * The search box filters the picker's options and posts nothing, so it has no field
              * error to carry; `SelectField` labels the control that actually sends `owner_id`,
              * directly beneath it. The same pair the account pickers use on the create screens.
              */}
            <div className="space-y-2">
              {ownersFailed ? null : (
                <SearchField
                  id="owner_search"
                  label={`Search ${OWNER_SEARCH[ownerKind].noun}`}
                  placeholder={OWNER_SEARCH[ownerKind].placeholder}
                  value={ownerSearch}
                  onChange={setOwnerSearch}
                />
              )}
              <SelectField
                id="owner_id"
                label={OWNER_LABEL[ownerKind]}
                required
                value={ownerId}
                onChange={(event) => {
                  const chosen = event.target.value;
                  setOwnerId(chosen);
                  setPinnedOwner(
                    chosen ? (ownerOptions.find((row) => String(row.id) === chosen) ?? null) : null
                  );
                }}
                error={fieldErrors.owner_id}
                hint={ownerHint}
              >
                <option value="">Choose a {OWNER_LABEL[ownerKind].toLowerCase()}</option>
                {ownerOptions.map((row) => (
                  <option key={row.id} value={row.id}>
                    {row.label}
                  </option>
                ))}
              </SelectField>
            </div>
          </>
        ) : null}

        {needsExam ? (
          <div className="space-y-2">
            {examsFailed ? (
              <Notice tone="warn">
                The exam list could not be loaded, so there is nothing to choose from. Close this
                dialog and open it again to retry.
              </Notice>
            ) : (
              <SearchField
                id="exam_search"
                label="Search exams"
                placeholder="Search by exam name…"
                value={examSearch}
                onChange={setExamSearch}
              />
            )}
            <SelectField
              id="exam_id"
              label="Exam"
              required
              value={examId}
              onChange={(event) => {
                const chosen = event.target.value;
                setExamId(chosen);
                setPinnedExam(chosen ? (examOptions.find((row) => String(row.id) === chosen) ?? null) : null);
              }}
              error={fieldErrors.exam_id}
              hint={examHint}
            >
              <option value="">Choose an exam</option>
              {examOptions.map((row) => (
                <option key={row.id} value={row.id}>
                  {examLabel(row)}
                </option>
              ))}
            </SelectField>
          </div>
        ) : null}

        <Field
          id="title"
          label="Title"
          maxLength={180}
          value={title}
          onChange={(event) => setTitle(event.target.value)}
          error={fieldErrors.title}
          hint="Optional — left blank, the server names it from the type and the owner."
        />

        <TextAreaField
          id="description"
          label="Description"
          rows={2}
          maxLength={255}
          value={description}
          onChange={(event) => setDescription(event.target.value)}
          error={fieldErrors.description}
          hint="Optional. Kept on the record."
        />
      </form>
    </Modal>
  );
}
